# Generated by Django 3.2.8 on 2022-08-19 10:22

from django.db import migrations, models
import employee_list.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.IntegerField()),
                ('name', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(default='applied', max_length=255)),
                ('contact', models.IntegerField(validators=[employee_list.models.phone_validator])),
                ('highest_degree', models.CharField(choices=[('None', 'None'), ('Matriculate', 'Matriculate'), ('Intermediate', 'Intermediate'), ('Bachelors', 'BLUBachelorsE'), ('Masters', 'Masters'), ('Doctoral', 'Doctoral')], default='None', max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('aadhaar', models.IntegerField(validators=[employee_list.models.aadhaar_validator])),
                ('DOB', models.DateField()),
                ('father_name', models.CharField(max_length=255, null=True)),
                ('gender', models.CharField(choices=[('None', 'None'), ('Male', 'Male'), ('Female', 'Female'), ('Not to disclose', 'Not to disclose')], default='None', max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
